INSERT INTO questions (
    topic_id, difficulty, question,
    option1, option2, option3, option4,
    correct_answer, explanation
) VALUES
(1, 'easy', 'What is an array?', 'A collection of same-type elements', 'A database query', 'A network device', 'An operating system', 'A collection of same-type elements', 'An array stores elements of the same data type in contiguous memory.'),
(1, 'easy', 'Which data structure follows FIFO?', 'Stack', 'Queue', 'Tree', 'Graph', 'Queue', 'Queue means First In, First Out.'),
(1, 'easy', 'Which data structure follows LIFO?', 'Queue', 'Stack', 'Array', 'Heap', 'Stack', 'Stack means Last In, First Out.'),
(1, 'easy', 'What is the root node of a tree?', 'Topmost node', 'Last node', 'Leaf node', 'Sibling node', 'Topmost node', 'The root is the first node in a tree structure.'),
(1, 'easy', 'Which of these is a linear data structure?', 'Tree', 'Graph', 'Array', 'Heap', 'Array', 'Array stores items in a sequential manner.'),
(1, 'easy', 'What does a linked list use to connect nodes?', 'Pointers', 'Indexes', 'Counters', 'Keys', 'Pointers', 'Each node stores a pointer to the next node.'),
(1, 'easy', 'In a singly linked list, each node points to?', 'Previous node', 'Next node', 'Root node', 'Parent node', 'Next node', 'A singly linked list points to the next node only.'),
(1, 'easy', 'Which data structure is used in recursion?', 'Stack', 'Queue', 'Graph', 'Heap', 'Stack', 'Function calls are managed using the call stack.'),
(1, 'easy', 'What is a leaf node?', 'Node with no children', 'Node with two children', 'Root node', 'Parent node', 'Node with no children', 'A leaf node has no child nodes.'),
(1, 'easy', 'How many children can a binary tree node have?', 'One', 'Two', 'Three', 'Four', 'Two', 'A binary tree node can have at most two children.'),
(1, 'easy', 'Which traversal visits root first?', 'Inorder', 'Postorder', 'Preorder', 'Level order', 'Preorder', 'Preorder traversal visits root before children.'),
(1, 'easy', 'Which traversal visits left, root, right?', 'Preorder', 'Inorder', 'Postorder', 'Level order', 'Inorder', 'Inorder traversal is left-root-right.'),
(1, 'easy', 'Which traversal visits left, right, root?', 'Preorder', 'Inorder', 'Postorder', 'DFS', 'Postorder', 'Postorder traversal is left-right-root.'),
(1, 'easy', 'What is a graph made of?', 'Nodes and edges', 'Rows and columns', 'Keys and values', 'Stacks and queues', 'Nodes and edges', 'A graph consists of vertices and edges.'),
(1, 'easy', 'What is the top element of a stack called?', 'Front', 'Rear', 'Top', 'Head', 'Top', 'The top is the last pushed item in a stack.'),
(1, 'easy', 'What is the first element of a queue called?', 'Front', 'Top', 'Bottom', 'Leaf', 'Front', 'Deletion in a queue happens from the front.'),
(1, 'medium', 'What is the time complexity of binary search?', 'O(n)', 'O(log n)', 'O(n log n)', 'O(1)', 'O(log n)', 'Binary search halves the search space each step.'),
(1, 'medium', 'Which data structure is best for implementing undo operations?', 'Queue', 'Stack', 'Tree', 'Graph', 'Stack', 'Undo operations use last-in-first-out behavior.'),
(1, 'medium', 'What is a circular queue?', 'Queue with one end connected to another', 'Queue with no front', 'Queue with two stacks', 'Queue with one element', 'Queue with one end connected to another', 'A circular queue connects the last position back to the first.'),
(1, 'medium', 'Which traversal uses a queue?', 'DFS', 'BFS', 'Inorder', 'Postorder', 'BFS', 'Breadth-first search uses a queue.'),
(1, 'medium', 'What is the time complexity of inserting at the beginning of a linked list?', 'O(1)', 'O(n)', 'O(log n)', 'O(n log n)', 'O(1)', 'Insertion at the head of a linked list is constant time.'),
(1, 'medium', 'Which data structure is used for breadth-first search?', 'Stack', 'Queue', 'Array', 'Heap', 'Queue', 'BFS explores level by level using a queue.'),
(1, 'medium', 'What is an adjacency matrix used for?', 'Representing graph edges', 'Representing stacks', 'Representing queues', 'Representing trees only', 'Representing graph edges', 'An adjacency matrix stores graph connections in matrix form.'),
(1, 'medium', 'What is the height of a tree?', 'Number of nodes', 'Longest path from root to leaf', 'Number of leaf nodes', 'Number of edges only', 'Longest path from root to leaf', 'Tree height is the longest path from root to any leaf.'),
(1, 'medium', 'What is a balanced binary tree?', 'Tree with equal left and right values', 'Tree where height difference is small', 'Tree with one node', 'Tree with no leaves', 'Tree where height difference is small', 'A balanced tree keeps subtree heights nearly equal.'),
(1, 'medium', 'Which structure stores key-value pairs?', 'Array', 'Hash table', 'Stack', 'Queue', 'Hash table', 'Hash tables map keys to values.'),
(1, 'medium', 'What is collision in hashing?', 'Two keys map to same index', 'Tree balance issue', 'Queue overflow', 'Stack underflow', 'Two keys map to same index', 'Collision occurs when different keys hash to the same slot.'),
(1, 'medium', 'What is the average search time in a hash table?', 'O(1)', 'O(n)', 'O(log n)', 'O(n log n)', 'O(1)', 'Hash tables provide constant average lookup time.'),
(1, 'hard', 'What is the worst-case time complexity of searching in a hash table?', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'O(n)', 'In worst case, many collisions may cause linear search.'),
(1, 'hard', 'Which tree traversal is used to evaluate expression trees?', 'Preorder', 'Inorder', 'Postorder', 'Level order', 'Postorder', 'Postorder evaluates children before the operator.'),
(1, 'hard', 'What is the time complexity of heapify operation?', 'O(log n)', 'O(n)', 'O(n log n)', 'O(1)', 'O(log n)', 'Heapify on one node takes logarithmic time.'),
(1, 'hard', 'Which structure is best for priority-based insertion and deletion?', 'Array', 'Queue', 'Heap', 'Linked list', 'Heap', 'Heaps are designed for priority access.'),
(1, 'hard', 'What is the time complexity of building a heap from n elements?', 'O(n)', 'O(n log n)', 'O(log n)', 'O(n^2)', 'O(n)', 'A heap can be built in linear time using bottom-up heapify.'),
(1, 'hard', 'In a binary search tree, what property holds?', 'Left subtree has greater values', 'Right subtree has smaller values', 'Left subtree has smaller values', 'All nodes are equal', 'Left subtree has smaller values', 'BST left children are smaller and right children are larger.'),
(1, 'hard', 'What is the time complexity of searching in a balanced BST?', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'O(log n)', 'Balanced BST search follows tree height, which is logarithmic.'),
(1, 'hard', 'Which data structure is used in backtracking algorithms?', 'Queue', 'Stack', 'Graph', 'Heap', 'Stack', 'Backtracking often uses recursion and the stack.'),
(1, 'hard', 'What is a trie mainly used for?', 'Sorting numbers', 'String searching', 'Matrix multiplication', 'Graph coloring', 'String searching', 'Tries are efficient for prefix-based string operations.'),
(1, 'hard', 'What is the time complexity of deleting a node in a linked list if the node pointer is given?', 'O(1)', 'O(n)', 'O(log n)', 'O(n log n)', 'O(1)', 'With direct access, deletion only needs pointer updates.'),
(1, 'hard', 'What is the time complexity of inorder traversal of a binary tree?', 'O(log n)', 'O(n)', 'O(n log n)', 'O(1)', 'O(n)', 'Every node is visited once in inorder traversal.'),
(1, 'hard', 'What is the advantage of linked list over array?', 'Random access', 'Fixed size', 'Dynamic size', 'Faster indexing', 'Dynamic size', 'Linked lists can grow and shrink dynamically.'),
(1, 'hard', 'Which graph traversal uses recursion naturally?', 'BFS', 'DFS', 'Dijkstra', 'Kruskal', 'DFS', 'Depth-first search is commonly implemented recursively.'),
(1, 'hard', 'What is the time complexity of inserting into a binary search tree on average?', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'O(log n)', 'Average insertion follows tree height in a balanced-like BST.'),
(1, 'hard', 'What is a min heap?', 'Parent is greater than children', 'Parent is smaller than children', 'All nodes equal', 'Only leaf nodes sorted', 'Parent is smaller than children', 'In a min heap, the smallest element is at the root.'),
(1, 'hard', 'What is a max heap?', 'Parent is smaller than children', 'Parent is greater than children', 'Left child smaller than right child', 'Root has no value', 'Parent is greater than children', 'In a max heap, the largest element is at the root.'),
(1, 'hard', 'Which sorting structure uses a heap?', 'Quick sort', 'Heap sort', 'Merge sort', 'Insertion sort', 'Heap sort', 'Heap sort builds and uses a heap data structure.'),
(1, 'hard', 'What is the space complexity of recursive factorial?', 'O(1)', 'O(n)', 'O(log n)', 'O(n log n)', 'O(n)', 'Recursive calls use stack space proportional to n.'),
(1, 'hard', 'Which traversal of a binary tree gives sorted order in BST?', 'Preorder', 'Inorder', 'Postorder', 'Level order', 'Inorder', 'Inorder traversal of a BST returns sorted keys.'),
(1, 'hard', 'Which operation is expensive in an array?', 'Accessing an element', 'Appending at end', 'Inserting in the middle', 'Reading first element', 'Inserting in the middle', 'Middle insertion requires shifting elements.'),
(1, 'hard', 'Which data structure supports both FIFO and LIFO concepts in some algorithms?', 'Stack', 'Queue', 'Deque', 'Array', 'Deque', 'Deque supports insertion and deletion at both ends.'),
(1, 'hard', 'What is a deque?', 'Double-ended queue', 'Depth-ended queue', 'Duplicate queue', 'Dynamic edge queue', 'Double-ended queue', 'A deque allows operations at both front and rear.'),
(1, 'hard', 'Which graph representation is better for sparse graphs?', 'Adjacency matrix', 'Adjacency list', 'Incidence table', 'Edge array only', 'Adjacency list', 'Adjacency lists use less memory for sparse graphs.'),
(1, 'hard', 'What is the time complexity of BFS on adjacency list?', 'O(V+E)', 'O(VE)', 'O(V^2)', 'O(log n)', 'O(V+E)', 'BFS visits each vertex and edge at most once.'),
(1, 'hard', 'What is the time complexity of DFS on adjacency list?', 'O(V+E)', 'O(VE)', 'O(V^2)', 'O(log n)', 'O(V+E)', 'DFS also processes each vertex and edge once.'),
(1, 'hard', 'Which data structure is ideal for implementing recursion?', 'Queue', 'Stack', 'Heap', 'Graph', 'Stack', 'Recursive function calls are stored on the call stack.');